const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.join(__dirname,'www');
(async()=>{const server=http.createServer((req,res)=>{const f=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(path.relative(root,f).startsWith('..')||!fs.existsSync(f)){res.statusCode=404;return res.end()}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res)}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const browser=await chromium.launch({...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{}),headless:true});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:'+server.address().port);
async function nav(k){await page.locator(`[data-view=${k}]`).click()}
async function add(k,title){await page.locator(`[data-new=${k}]`).click();await page.locator('[name=title]').fill(title)}
async function save(){await page.locator('#editor button[type=submit]').click()}
await nav('goals');await add('goals','خواندن کتاب');await page.locator('[name=target]').fill('۲۰۰');await page.locator('[name=current]').fill('۵۰');await page.locator('[name=unit]').fill('صفحه');await save();assert(await page.locator('progress').getAttribute('value')==='25');
await nav('tasks');await add('tasks','مطالعهٔ امروز');await page.locator('[name=subs]').fill('۲۰ صفحه بخوان\nنکته‌ها را یادداشت کن');await page.locator('#fields summary').click();const goal=await page.evaluate(()=>state.goals[0].id);await page.locator('[name=goalId]').selectOption(goal);await save();await page.getByText('زیرکارها',{exact:true}).click();await page.locator('[data-sub]').first().click();await page.locator('[data-check]').click();assert.equal(await page.evaluate(()=>state.tasks[0].done),true);await page.locator('[data-filter=done]').click();await page.locator('[data-edit=tasks]').click();await page.locator('[name=title]').fill('مطالعه و مرور');await save();assert.equal(await page.evaluate(()=>state.tasks[0].subs[0].done),true);
await nav('money');await add('money','خرید کتاب');await page.locator('[name=amount]').fill('۱۰۰٬۰۰۰');await save();await add('money','درآمد پروژه');await page.locator('[name=amount]').fill('۵۰۰۰۰۰');await page.locator('[name=kind]').selectOption('income');await save();await page.locator('[data-budget]').click();await page.locator('[name=amount]').fill('۲۰۰۰۰۰');await save();assert.equal(await page.evaluate(()=>state.money.reduce((s,x)=>s+(x.kind==='income'?x.amount:-x.amount),0)),400000);
await nav('habits');await add('habits','پیاده‌روی روزانه');await save();await page.locator('[data-habit]').first().click();assert.equal(await page.evaluate(()=>streak(state.habits[0])),1);await page.locator('[data-habit]').first().click();assert.equal(await page.evaluate(()=>streak(state.habits[0])),0);
await nav('planner');await add('tasks','کار فردا');await page.locator('[name=day]').selectOption('1');await save();await page.reload();assert.equal(await page.evaluate(()=>state.tasks.length),2);assert.equal(await page.evaluate(()=>state.budget),200000);
assert.equal(await page.evaluate(()=>parseJalali(jalali(today()))===today()),true);assert.equal(await page.evaluate(()=>{try{parseJalali('1405/13/01');return false}catch{return true}}),true);
const backup=await page.evaluate(()=>JSON.stringify(state));await page.evaluate(()=>change(d=>d.tasks=[]));await page.evaluate(raw=>receiveBackup(raw),backup);assert.equal(await page.evaluate(()=>state.tasks.length),2);
assert.equal(await page.evaluate(()=>{const old=JSON.stringify(state);receiveBackup('{bad');return JSON.stringify(state)===old}),true);
assert.equal(await page.evaluate(()=>{const b=structuredClone(state);b.tasks[0].id='"><script>';try{validateBackup(b);return false}catch{return true}}),true);
await nav('tasks');await page.locator('[data-filter=all]').click();await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.screenshot({path:path.join(__dirname,'personal-light.png')});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:path.join(__dirname,'personal-dark.png')});
await add('tasks','بررسی فرم');await page.screenshot({path:path.join(__dirname,'personal-form.png')});await page.locator('#close').click();await page.setViewportSize({width:1024,height:800});await page.screenshot({path:path.join(__dirname,'personal-desktop.png')});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
const nativePage=await browser.newPage();await nativePage.addInitScript(()=>{window.PersonalNative={readState:()=>localStorage.getItem('native-test')||'',writeState:raw=>{if(window.failWrite)return false;localStorage.setItem('native-test',raw);return true},exportBackup:raw=>window.exported=raw,importBackup:()=>window.importOpened=true}});await nativePage.goto('http://127.0.0.1:'+server.address().port);
assert.equal(await nativePage.evaluate(()=>change(d=>d.budget=12345)),true);await nativePage.reload();assert.equal(await nativePage.evaluate(()=>state.budget),12345);assert.equal(await nativePage.evaluate(()=>{window.failWrite=true;return change(d=>d.budget=1)}),false);assert.equal(await nativePage.evaluate(()=>state.budget),12345);await nativePage.evaluate(()=>exportBackup());assert.equal(await nativePage.evaluate(()=>JSON.parse(window.exported).budget),12345);await nativePage.close();
console.log('PASS: tasks/subtasks/edit/complete, goals/progress, income/expense/budget, habits, planner, persistence, Jalali dates, backup restore and malformed backup rejection, mobile/dark/light/desktop');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
