name: gen-keystore
on:
  workflow_dispatch:
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: keytool -genkeypair -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10950 -dname "CN=Android Debug,O=Android,C=US"
      - uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: debug.keystore
